### ISSUE TITLE
BUG: Projected Textures do not seem to be capable of being parented.

### ISSUE THREAD

**Issue by OssyFlawol** [OssyFlawol/portalcollab#2]
Self explanatory title, I made a test map for this which should be helpful in debugging.
https://i.gyazo.com/942246346eb718a50b0070b469152a83.mp4

https://cdn.discordapp.com/attachments/1140105171213484064/1140924349558296586/ptex_test.bsp
https://cdn.discordapp.com/attachments/1140105171213484064/1140924349868670976/ptex_test.vmf

**Comment by Aarik1** [comment]
Mapbase port fixed this bug
