### ISSUE TITLE
Energy pellet customization

### ISSUE THREAD

**Issue by vrad-exe** [OssyFlawol/portalcollab#5]
Add extra keyvalues to `point_energy_ball_launcher` to enable configuring various extra settings about the energy pellets:

- If the pellets should collide with and kill players
- The sprites used by the energy pellets (I think there's 2 that are layered)
- The idle sound emitted while the pellet flies around

The reason I included the latter 2 suggestions is for the final connected mod. If one person makes a map where energy pellet collisions are turned off, but another person makes a map where having the collisions turned on is necessary, it'd be confusing to have some energy pellets which do collide and some which don't, so this would allow changing the non-colliding ones to use a different texture and idle sound in order to differentiate them.

**Comment by SpAMCAN** [comment]
Would it be possible to get custom model support too? I was faffing about trying to set up a custom energy ball model yesterday, to no avail

**Comment by vrad-exe** [comment]
The model is only used when you grab energy balls with the gravity gun, when flying around they're just sprites. So that would probably be good to have too, but isn't specifically needed unless you're making a map involving the gravity gun and energy balls.

**Comment by SpAMCAN** [comment]
19 years of playing Half-Life 2 and I never knew that.

**Comment by WonderlandWar** [comment]
Most of your requests have been added
