### ISSUE TITLE
Fix 90 FOV crosshair colors

### ISSUE THREAD

**Issue by vrad-exe** [OssyFlawol/portalcollab#6]
Old builds of Portal and HL2 had a bug where when on 90 FOV, the zoomed/unzoomed crosshair colors would be flipped, so it would be yellow when zoomed out and white when zoomed in instead of the reverse. Since Portal maps typically don't give you the ability to zoom, this effectively meant the crosshair just turned yellow on 90 FOV for no reason.

This was fixed in a recent update, with the cvar `hud_invert_zoomed_unzoomed_crosshair_colors` added to restore the bugged behavior if the player preferred it. Since the code used for PortalCollab predates this update, it currently still has the bug. This should be fixed, and the cvar added.

**Comment by vrad-exe** [comment]
So wonderland war and I looked into this further and it's really weird. In every version of HL2 since 2006 or earlier, there is an explicit check to make the crosshair yellow if FOV >= 90, with surrounding comments implying the intended behavior was for it to be yellow by default and turn white when zoomed in. But before sometime in 2008 or so, there was no option to change the FOV from the default 75, so in practice the crosshair would have always been white. Then I guess in one of the recent updates (Josh?) noticed that the code wasn't working and decided to restore the ostensibly "intended" behavior of being yellow when unzoomed, and added the cvar which creates the *completely new* behavior of being white when unzoomed and yellow when zoomed, with no option to restore the original always-white behavior.

Perhaps we should add like `hud_crosshair_color_mode` which lets you choose between the three, or just make it always white since that's how it probably looked for 90% of players until recently and is what Portal 2 did.

...Portal 2 doesn't still have a yellow crosshair, right...?

**Comment by WonderlandWar** [comment]
The crosshair will now always appear white regardless of FOV.
